apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: medsync
type: Opaque
stringData:
  DB_PASSWORD: "postgres"
  JWT_SECRET: "medical-platform-secret"
  ADMIN_EMAIL: "admin@medsync.local"
  ADMIN_PASSWORD: "admin123"
  ADMIN_FULL_NAME: "Clinic Administrator"
  GF_SECURITY_ADMIN_PASSWORD: "admin"
