global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alert.rules.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: postgres-exporter
    scrape_interval: 10s
    static_configs:
      - targets: ["postgres-exporter:9187"]
        labels:
          service: postgres
          tier: database

  - job_name: auth-service
    metrics_path: /metrics
    scrape_interval: 10s
    static_configs:
      - targets: ["auth-service:8082"]
        labels:
          service: auth-service
          tier: application

  - job_name: patient-service
    metrics_path: /metrics
    scrape_interval: 10s
    static_configs:
      - targets: ["patient-service:8083"]
        labels:
          service: patient-service
          tier: application

  - job_name: doctor-service
    metrics_path: /metrics
    scrape_interval: 10s
    static_configs:
      - targets: ["doctor-service:8080"]
        labels:
          service: doctor-service
          tier: application

  - job_name: appointment-service
    metrics_path: /metrics
    scrape_interval: 10s
    static_configs:
      - targets: ["appointment-service:8081"]
        labels:
          service: appointment-service
          tier: application

  - job_name: chat-service
    metrics_path: /metrics
    scrape_interval: 10s
    static_configs:
      - targets: ["chat-service:8084"]
        labels:
          service: chat-service
          tier: application
